/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        surface: '#f9f9ff',
        'surface-dim': '#cfdaf1',
        'surface-bright': '#f9f9ff',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f0f3ff',
        'surface-container': '#e7eeff',
        'surface-container-high': '#dee8ff',
        'surface-container-highest': '#d8e3fa',
        'on-surface': '#111c2c',
        'on-surface-variant': '#414750',
        'inverse-surface': '#263142',
        'inverse-on-surface': '#ebf1ff',
        outline: '#727782',
        'outline-variant': '#c1c7d2',
        'surface-tint': '#1960a3',
        primary: '#005394',
        'on-primary': '#ffffff',
        'primary-container': '#2b6cb0',
        'on-primary-container': '#e1ecff',
        'inverse-primary': '#a2c9ff',
        secondary: '#13696a',
        'on-secondary': '#ffffff',
        'secondary-container': '#a2eded',
        'on-secondary-container': '#1a6d6e',
        tertiary: '#784600',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#9a5b00',
        'on-tertiary-container': '#ffe7d2',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        'primary-fixed': '#d3e4ff',
        'primary-fixed-dim': '#a2c9ff',
        'on-primary-fixed': '#001c38',
        'on-primary-fixed-variant': '#004881',
        'secondary-fixed': '#a5eff0',
        'secondary-fixed-dim': '#89d3d4',
        'on-secondary-fixed': '#002020',
        'on-secondary-fixed-variant': '#004f50',
        'tertiary-fixed': '#ffdcbd',
        'tertiary-fixed-dim': '#ffb86e',
        'on-tertiary-fixed': '#2c1600',
        'on-tertiary-fixed-variant': '#693c00',
        background: '#f9f9ff',
        'on-background': '#111c2c',
        'surface-variant': '#d8e3fa',
        success: '#146c2e',
        'success-container': '#d3f5dd',
      },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-sm': ['24px', { lineHeight: '32px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-sm': ['18px', { lineHeight: '24px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'body-sm': ['13px', { lineHeight: '18px', fontWeight: '400' }],
        'label-md': ['12px', { lineHeight: '16px', letterSpacing: '0.02em', fontWeight: '500' }],
        'table-data': ['13px', { lineHeight: '16px', fontWeight: '400' }],
      },
      borderRadius: {
        sm: '0.125rem',
        DEFAULT: '0.25rem',
        md: '0.375rem',
        lg: '0.5rem',
        xl: '0.75rem',
        full: '9999px',
      },
      spacing: {
        'container-padding': '1.5rem',
        'element-gap': '0.75rem',
        'sidebar-width': '240px',
        'drawer-width': '400px',
      },
      boxShadow: {
        drawer: '-4px 0 24px rgba(0,0,0,0.05)',
        elevated: '0px 4px 12px rgba(0,0,0,0.05)',
      },
    },
  },
  plugins: [require('@tailwindcss/forms')],
};
