export const ROUTES = {
  LOGIN: '/login',
  DASHBOARD: '/',
  RECEPTION_HOME: '/home/reception',
  DOCTOR_HOME: '/home/doctor',
  QA_HOME: '/home/qa',
  APPOINTMENTS: '/appointments',
  APPOINTMENT_BOOKING: '/appointments/book',
  PATIENTS: '/patients',
  STAFF: '/staff',
  BILLING: '/billing',
  CONSULTATION: '/consultation/:appointmentId',
  WALK_IN: '/walk-in',
  REPORTS: '/reports',
} as const;
